feed/urls.py
from django.conf.urls import url 
from . import views


urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^signup/$',views.signup,name='signup'),
	url(r'^friends/(?P<pk>[0-9]+)/$',views.friends,name='friends'),
	url(r'^profile/(?P<pk>[0-9]+)/$',views.profile,name='profile'),
	url(r'^friends/profile/(?P<name>[a-zA-Z0-9]+)/',views.fprofile,name='f-profile'),
	url(r'^profile/(?P<user_id>[0-9]+)/add/$',views.add_profile,name='add-profile'),
	url(r'^profile/post/add/$',views.add_post,name='add-post'),
	url(r'^profile/(?P<pk>[0-9]+)/update/$',views.UpdateUserProfile.as_view(),name='update-profile'),
	url(r'^profile/(?P<pk>[0-9]+)/status/$',views.UpdateStatus.as_view(),name='status'),
	url(r'^friends/(?P<pk>[0-9]+)/sent/$',views.sent_friend,name='sent-friend'),
	url(r'^notification/$',views.notify,name='notification'),
	url(r'^notification/confirm/(?P<name>[a-zA-Z0-9]+)/$',views.confirm_yes,name='confirm-yes'),
	url(r'^notification/remove/(?P<name>[a-zA-Z0-9]+)/$',views.remove_yes,name='remove-yes'),
	url(r'^notification/confirm_no/(?P<name>[a-zA-Z0-9]+)/$',views.confirm_no,name='confirm-no'),
	url(r'^post/(?P<pk>[0-9]+)/like/$',views.like_yes,name='like-yes'),
	url(r'^chatroom/(?P<frnd>[a-zA-Z0-9]+)/$',views.chatroom,name='chatroom'),
	url(r'^post/(?P<pk>[0-9]+)/$',views.show_post,name='show_post'),
	url(r'^post/comment/(?P<pk>[0-9]+)/$',views.add_comment,name='add_comment'),
]

frnzfeed/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^',include('feed.urls')),
]

if settings.DEBUG:
	urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
	urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils import timezone


class UserProfile(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True,)
	photo = models.FileField()
	phone_no = models.IntegerField()
	status = models.CharField(max_length=1000)

	def ___str__(self):
		return self.phone_no

class Post(models.Model):
	user = models.ForeignKey(User,on_delete=models.CASCADE)
	pic = models.FileField()
	quote = models.CharField(max_length=3000)
	likes = models.IntegerField(default=0)
	date = models.DateTimeField(auto_now_add=True)

	def ___str__(self):
		return self.pk

class Friend(models.Model):
	name = models.CharField(max_length=300)
	user = models.ManyToManyField(User)

	def ___str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('friends',args=[str(self.id)])

class Rqst(models.Model):
	receiver = models.CharField(max_length=300)
	sender = models.CharField(max_length=300)

	def ___str__(self):
		return self.sender + '-' + self.receiver

class Like(models.Model):
	post = models.ForeignKey(Post,on_delete=models.CASCADE)
	user_id = models.IntegerField(default=None)

class Clients(models.Model):
	name = models.CharField(max_length=300)
	ch_name = models.CharField(max_length=1000)

	def ___str__(self):
		return self.name

class Messages(models.Model):
	to = models.CharField(max_length=300)
	frm = models.CharField(max_length=300)
	message = models.TextField()
	date = models.DateTimeField(auto_now_add=True)

	def ___str__(self):
		return self.to+'-'+self.frm

class Comments(models.Model):
	post = models.ForeignKey(Post,on_delete=models.CASCADE)
	user = models.CharField(max_length=300,default='admin')
	comment = models.TextField()
	date = models.DateTimeField(auto_now_add=True,null=True)

	def ___str__(self):
		return self.comment

feed/forms.py
from django import forms
from .models import UserProfile, Post

class ProfileForm(forms.ModelForm):

	class Meta:
		model = UserProfile
		fields = ['photo','phone_no','status']


class PostForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ['pic','quote']

feed/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.forms import  UserCreationForm
from django.urls import reverse
from django.utils.safestring import mark_safe
import json
from django.contrib.auth import authenticate, login
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.models import User
from .forms import ProfileForm, PostForm
from .models import Post, UserProfile, Rqst, Friend, Like, Messages, Comments



@login_required
def index(request):
	user = request.user
	friend_list = []
	for friend in user.friend_set.all():
		friend_list.append(friend.name)
	post_list = Post.objects.order_by('-date')
	query = request.GET.get('q')
	all_users = User.objects.all()
	if query:
		results = all_users.filter(Q(username__icontains=query)).distinct()
		return render(request,'feed/search_result.html',{'results':results,'friend_list':friend_list})
	return render(request,'feed/index.html',{'friend_list':friend_list,'post_list':post_list})


def signup(request):
	form = UserCreationForm()
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			user = form.save()
			username = form.cleaned_data.get('username')
			raw_password = form.cleaned_data.get('password1')
			user = authenticate(username=username,password=raw_password)
			login(request, user)
			request.method = 'GET'
			return render(request,'feed/signedup.html',{'user':user})
	return render(request,'feed/signup.html',{'form':form})

def profile(request,pk):
	user = get_object_or_404(User,pk=pk)
	post_list = user.post_set.order_by('-date')
	return render(request,'feed/profile.html',{'user':user,'post_list':post_list})

def friends(request,pk):
	user = get_object_or_404(User,pk=pk)
	users = User.objects.all()
	friends = user.friend_set.all()
	friend_list = []
	for x in friends:
		friend_list.append(x.name)
	return render(request,'feed/friends.html',{'friends':friends,'users':users,'friend_list':friend_list})

def add_profile(request,user_id):
	user = get_object_or_404(User,pk=user_id)
	form = ProfileForm(request.POST or None,request.FILES or None)
	if form.is_valid():
		profile = form.save(commit=False)
		profile.photo = request.FILES['photo']
		profile.user = user
		profile.save()
		obj = Friend.objects.create(name=request.user.username)
		obj.save()
		return redirect('profile',user_id)
	return render(request,'feed/profile_form.html',{'form':form})

def fprofile(request,name):
	user = get_object_or_404(User,username=name)
	return render(request,'feed/fprofile.html',{'user':user})


def add_post(request):
	form = PostForm(request.POST or None,request.FILES or None)
	if form.is_valid():
		post = form.save(commit=False)
		post.pic = request.FILES['pic']
		post.user = request.user
		post.save()
		return redirect(profile,request.user.id)
	return render(request,'feed/profile_form.html',{'form':form})

class UpdateStatus(UpdateView):
	model = UserProfile
	fields = ['status']
	success_url = '/' 


class UpdateUserProfile(UpdateView):
	model = UserProfile
	fields = ['photo','status','phone_no'] 
	success_url = '/'

def sent_friend(request,pk):
	user = get_object_or_404(User,pk=pk)
	obj = Rqst.objects.create(receiver=user.username,sender = request.user.username)
	obj.save()
	return render(request,'feed/request_sent.html',{})

def notify(request):
	obj = Rqst.objects.filter(receiver=request.user.username)
	return render(request,'feed/notify.html',{'obj':obj})

def confirm_yes(request,name):
	user = get_object_or_404(User,username=name)
	obj = get_object_or_404(Friend,name=request.user.username)
	obj.user.add(user)
	obj.save()
	obj = get_object_or_404(Friend,name=user.username)
	obj.user.add(request.user)
	obj.save()
	Rqst.objects.filter(sender=user.username,receiver=request.user.username).delete()
	return redirect('friends',request.user.id)

def confirm_no(request,name):
	user = get_object_or_404(User,username=name)
	Rqst.objects.filter(sender=user.username,receiver=request.user.username).delete()
	return redirect('friends',request.user.id)

def like_yes(request,pk):
	obj = get_object_or_404(Post,pk=pk)
	list = obj.like_set.all()
	for x in list:
		if x.user_id == request.user.id:
			return HttpResponseRedirect( request.GET.get('next'))
	obj1 = Like.objects.create(post=obj,user_id=request.user.id)
	obj.likes = obj.like_set.count()
	obj.save()
	return HttpResponseRedirect( request.GET.get('next'))


def remove_yes(request,name):
	user = get_object_or_404(User,username=name)
	obj = get_object_or_404(Friend,name=request.user.username)
	obj.user.remove(user)
	obj.save()
	obj = get_object_or_404(Friend,name=user.username)
	obj.user.remove(request.user)
	obj.save()
	return redirect('friends',request.user.id)

def sort_helper(elm):
	return elm.date

def chatroom(request,frnd):
	name=request.user.username
	user = get_object_or_404(User,username=frnd)
	receiver = user.username
	mymsg = Messages.objects.filter(to=receiver,frm=name)
	urmsg = Messages.objects.filter(to=name,frm=receiver)
	msgs = []
	msgs += mymsg
	msgs += urmsg
	msgs.sort(key=sort_helper,reverse=True)
	return render(request,'feed/chatroom.html',{
		'receiver':receiver,
		'name_json':mark_safe(json.dumps(name)),
		'msgs':msgs
		})

def show_post(request,pk):
	obj = get_object_or_404(Post,pk=pk)
	return render(request,'feed/show_post.html',{'obj':obj,})

def add_comment(request,pk):
	if request.POST['comment']=='':
		return redirect('index')
	post = get_object_or_404(Post,pk=pk)
	obj = Comments.objects.create(post=post,comment=request.POST['comment'],user=request.user.username)
	obj.save()
	return redirect('show_post',post.id)

feed/templates/feed/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}MusicZone{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
<style type="text/css">
  {% block style %}
  {% endblock %}
</style>
</head>
<body>
{% block navbar %}
<div>
    <nav class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'index' %}">FrnzFeed</a>
        </div>
        {% if user.is_authenticated %}
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            
            <li class="active"><a href="{% url 'index' %}">Home</a></li>
            
            <li><a href="{% url 'profile' request.user.id %}">Profile</a></li>
            <li><a href="{% url 'friends' request.user.id %}">Friends</a></li>
            <li><a href="{% url 'add-post' %}">Add Posts</a></li>
            <li><a href="{% url 'notification' %}">Notifications</a></li>
          </ul>
          <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
          <li class="disable"><a href="#">Welcome, {{ request.user.username }}</a></li>
            <li><a href="{% url 'logout' %}">Logout</a></li>
                       
          </ul>
        </div>
         {% endif %}
         <!--/.nav-collapse -->
      </div>
    </nav>
</div>
{% endblock %}

{% block content %}
{% endblock %}
</body>
<script>
  {% block script %}
  {% endblock %}
</script>
</html>

feed/templates/feed/chatroom.html
{% extends 'feed/base.html' %}

{% block style %}
.blue_box, .green_box {
    display: block;
    clear:both;
}
.blue_box span {
    background-color: blue;
    color: white;
    padding: 10px 5px;
    display: block;
    float: right;
    border-radius:10px;
}
.green_box span {
    background-color: green;
    color: white;
    padding: 10px 5px;
    display: block;
    float: left;
    border-radius:10px;
}
{% endblock %}

{% block content %}
	<center><h2>{{receiver}}</h2></center>
	<center><hr style="width: 50%"></center>
	<div style="height: 400px;margin: 20px;padding: 20px;width: 70%;overflow: scroll;margin-left: 50px;" id="disp_msg">
        {% for msg in msgs %}
            {% if msg.to == receiver %}
                <div class="blue_box"><span>{{msg.message}}</span></div> 
            {% else %}
                <div class="green_box"><span>{{msg.message}}</span></div>
            {% endif %}
        {% endfor %}
	</div>
	<input type="text" name="msg" id="msg" style="width: 70%;margin-left: 50px" placeholder="message..."><br>
	<button class="btn btn-success" onclick="fun(this)" value={{receiver}} style="margin-left: 50px">Send</button>
{% endblock %}

{% block script %}
	var roomName = {{ name_json }};

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/' + roomName + '/');

    chatSocket.onclose = function(e) {
        console.error('Chat socket closed unexpectedly');
    };

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var message = data['message'];
        var sender = data['sender'];
        if(sender==roomName){
            document.getElementById('disp_msg').innerHTML = '<div class="blue_box"><span>'+ message +'</span></div>' + document.getElementById('disp_msg').innerHTML;
        }
        else{
            document.getElementById('disp_msg').innerHTML = '<div class="green_box"><span>'+ message +'</span></div>' + 
            document.getElementById('disp_msg').innerHTML;
        }
    };

    function fun(x) {
        message = document.getElementById('msg').value;
        if(message!=''){
        document.getElementById('msg').value = '';
        chatSocket.send(JSON.stringify({
            'value':0,
            'receiver': x.value,
            'message': message
        }));
    }   
    }
{% endblock %}

feed/templates/feed/form-template.html
{% for field in form %}
<div class="form-group row">
	<div class="col-sm-12"><span class="text-danger small">{{ field.error }}</span></div>
	<div class="col-sm-3"><label class="control-label col-sm-2">{{ field.label_tag }}</label></div>
	<div class="col-sm-9">{{ field }}</div>
</div>
{% endfor %}

feed/templates/feed/fprofile.html
{% extends 'feed/base.html' %}

{% block content %}
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-6 col-md-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'profile' user.id %}">
                        {% if user.userprofile.photo %}
                            <img src="{{ user.userprofile.photo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ user.username }}</h1>
                    <h4 style="color: #4d4d4d">{{ user.userprofile.status }}</h4>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-6 col-md-8">

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>{{user.username}}'s Posts :</h3>
                    <hr>
                    {% for post in user.post_set.all %}
						<div class="row">
							<div class="col-sm-3"></div>
							<div class="col-sm-8 col-lg-6">
				                    <div class="thumbnail">
				                        <a href="{% url 'show_post' post.id %}">
				                            <div style="height: 200px">
				                                <center><img src="{{ post.pic.url }}" class="img-responsive" style="height: 190px"></center>
				                                <hr>
				                            </div>
				                        </a>
				                        <div class="caption">
				                        	<h2><b>{{ post.user.username }}</b></h2>
				                            <h5 style="color:#595959">&emsp; {{ post.quote }}</h5>
				                        </div>
				                            <a href="{% url 'like-yes' post.id %}?next={{ request.path }}" class="btn btn-warning">
				                                <span class="glyphicon glyphicon-heart"></span>&emsp; {{ post.likes }}
				                            </a><br><br>
				                            <form method="post" action="{% url 'add_comment' post.id %}">
												{% csrf_token %}
												<input type="text" name="comment" id="comment" placeholder="Add comment ...">
												<input type="submit" name="ok_cmnt">
											</form>
				                    </div>
				                </div>
						</div>
					{% endfor %}
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

feed/templates/feed/friends.html
{% extends 'feed/base.html' %}

{% block content %}
<!--	<ul>
		{% for friend in friends %}
			<li><a href="{% url 'f-profile' friend.name %}">{{ friend.name }}</a><br>
			<a href="{% url 'remove-yes' friend.name %}" class="btn btn-success">Remove</a></li>
		{% endfor %}
		<h3>suggested: </h3>
		{% for friend in users %}
		{% if not friend == request.user and not friend.username == 'admin' and not friend.username in friend_list %}
			<li><a href="{% url 'f-profile' friend.username %}">{{ friend.username }}</a><br>
				<a href="{% url 'sent-friend' friend.id %}" class="btn btn-info">Follow</a>
			</li>
		{% endif %}
		{% endfor %}
	</ul>-->
	<div class="row"><div class="col-md-1"></div>
	<div class="col-md-5">
		<ul class="list-group">
			<h3>Friends List: </h3>
			{% for friend in friends %}
				<li class="list-group-item list-group-item-success"><strong><a href="{% url 'f-profile' friend.name %}">{{ friend.name }}</a></strong>
			<a href="{% url 'remove-yes' friend.name %}" class="btn btn-sm btn-danger" style="float: right;margin-left: 10px;">Remove</a>
			<a href="{% url 'chatroom' friend.name %}" class="btn btn-sm btn-success" style="float: right;">Chat</a>
		</li>
			{% endfor %}
		</ul>
	</div>
	<div class="col-md-5">
		<ul class="list-group">
			<h3>Suggested Friends: </h3>
			{% for friend in users %}
			{% if not friend == request.user and not friend.username == 'admin' and not friend.username in friend_list %}
				<li class="list-group-item list-group-item-info"><strong><a href="{% url 'f-profile' friend.username %}">{{ friend.username }}</a></strong>
					<small><a href="{% url 'sent-friend' friend.id %}" class="btn btn-sm btn-success" style="float: right;">Follow</a></small>
				</li>
			{% endif %}
			{% endfor %}
		</ul>
	</div><div class="col-md-1"></div>
</div>
{% endblock %}

feed/templates/feed/index.html
{% extends 'feed/base.html' %}

{% block content %}

<div class="container">
	{% for post in post_list %}
		{% if post.user.username in friend_list %}
		<div class="row">
			<div class="col-sm-3"></div>
			<div class="col-sm-8 col-lg-6">
                    <div class="thumbnail">
                        <a href="{% url 'show_post' post.id %}">
                            <div style="height: 200px">
                                <center><img src="{{ post.pic.url }}" class="img-responsive" style="height: 190px"></center>
                                <hr>
                            </div>
                        </a>
                        <div class="caption">
                            <h2><b>{{ post.user.username }}</b></h2>
                            <h5 style="color:#595959">&emsp; {{ post.quote }}</h5>
                        </div>
                            <a href="{% url 'like-yes' post.id %}?next={{ request.path }}" class="btn btn-warning">
                                <span class="glyphicon glyphicon-heart"></span>&emsp; {{ post.likes }}
                            </a><br><br>
                            <form method="post" action="{% url 'add_comment' post.id %}">
								{% csrf_token %}
								<input type="text" name="comment" id="comment" placeholder="Add comment ...">
								<input type="submit" name="ok_cmnt">
							</form>
                    </div>
                </div>
		</div>
		{% endif %}
	{% endfor %}
</div>
{% endblock %}

feed/templates/feed/notify.html
{% extends 'feed/base.html' %}

{% block content %}
<div>
	{% if not obj %}
	<h2>no notifications yet.</h2>
	{% endif %}
	{% for ids in obj %}
	<div>
		<h3>{{ ids.sender }}</h3>
		<a href="{% url 'confirm-yes' ids.sender %}" class="btn btn-success">Confirm</a> <a href="{% url 'confirm-no' ids.sender %}" class="btn btn-danger">Delete</a>
	</div>
	{% endfor %}
</div>
{% endblock %}

feed/templates/feed/profile.html
{% extends 'feed/base.html' %}

{% block content %}

<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-6 col-md-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'profile' user.id %}">
                        {% if user.userprofile.photo %}
                            <img src="{{ user.userprofile.photo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ user.username }}</h1>
                    <h4 style="color: #4d4d4d">{{ user.userprofile.status }}</h4>
                    <a href="{% url 'status' user.id %}" class="btn btn-success">Update Status</a>
                    <a href="{% url 'update-profile' user.id %}" class="btn btn-warning">Edit Profile</a>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-6 col-md-8">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'add-post' %}">Add Post</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>My Posts :</h3>
                    <hr>
                    {% for post in post_list %}
						<div class="row">
							<div class="col-sm-3"></div>
							<div class="col-sm-8 col-lg-6">
				                    <div class="thumbnail">
				                        <a href="{% url 'show_post' post.id %}">
				                            <div style="height: 200px">
				                                <center><img src="{{ post.pic.url }}" class="img-responsive" style="height: 190px"></center>
				                                <hr>
				                            </div>
				                        </a>
				                        <div class="caption">
				                            <h5 style="color:#595959">&emsp; {{ post.quote }}</h5>
				                        </div>
				                            <a href="{% url 'like-yes' post.id %}?next={{ request.path }}" class="btn btn-warning">
				                                <span class="glyphicon glyphicon-heart"></span>&emsp; {{ post.likes }}
				                            </a><br><br>
				                            <form method="post" action="{% url 'add_comment' post.id %}">
												{% csrf_token %}
												<input type="text" name="comment" id="comment" placeholder="Add comment ...">
												<input type="submit" name="ok_cmnt">
											</form>
				                    </div>
				                </div>
						</div>
					{% endfor %}
                </div>
            </div>

        </div>

    </div>

</div>
	
{% endblock %}

feed/templates/feed/profile_form.html
{% extends 'feed/base.html' %}

{% block content %}
<div class="jumbotron" style="border-radius: 20px">
	<form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{% include 'feed/form-template.html' %}
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<button class="btn btn-success" type="submit">Submit</button>
			</div>
		</div>
	</form>
</div>
{% endblock %}

feed/templates/feed/request_sent.html
{% extends 'feed/base.html' %}

{% block content %}
<p>sent</p>
{% endblock %}

feed/templates/feed/show_post.html
{% extends 'feed/base.html' %}

{% block content %}

<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-6 col-md-4">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'show_post' obj.id %}">
                        {% if obj.pic %}
                            <img src="{{ obj.pic.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ obj.user.username }}</h1>
                    <h4 style="color: #4d4d4d">{{ obj.quote }}</h4>
                    <a href="{% url 'like-yes' obj.id %}?next={{ request.path }}" class="btn btn-warning col-lg-3"><span class="glyphicon glyphicon-heart"></span>&emsp; {{ obj.likes }}</a>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-6 col-md-8">

        	<div class="jumbotron">
        		<form method="post" action="{% url 'add_comment' obj.id %}">
						{% csrf_token %}
						<input type="text" name="comment" id="comment" placeholder="Add comment ..." style="padding: 10px;border-radius: 10px;width: 80%;margin-right: 10px">
						<input type="submit" name="ok_cmnt" value="comment" class="btn btn-bg btn-success">
					</form>
            </div>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>Comments :</h3>
                    <hr>
                    {% for comment in obj.comments_set.all %}
						<div class="row">
							<div class="col-sm-3">
								<h4>{{comment.user}}</h4>
							</div>
							<div class="col-sm-8 col-lg-6">
				            	<h5>{{ comment.comment }}</h5>	       
				            </div>
				            </div>
						</div>
					{% endfor %}
                </div>
            </div>

        </div>

    </div>

</div>
{% endblock %}

feed/templates/feed/signedup.html
{% extends 'feed/base.html' %}
{% if cmt == 'add-profile' %}
{% block navbar %}
{% endblock %}
{% endif %}

{% block content %}
<div class="jumbotron">
	<h3>Hello, {{ user.username }}. You have successfully logged in.</h3>
	<a href="{% url 'add-profile' user.id %}" class="btn btn-info">Edit your profile</a>
</div>
{% endblock %}

feed/templates/feed/signup.html
{% extends 'feed/base.html' %}

{% block content %}
  <form action="{% url 'signup' %}" method="post">
    {% csrf_token %}
    {% for field in form %}
      <div>
        {{ field.label_tag }}
        {{ field }}
      </div>
    {% endfor %}
    <button type="submit">Sign up</button>
    <p>Already have an account? <a href="{% url 'login' %}">Log in!</a></p>
  </form>
{% endblock content %}

feed/templates/feed/userprofile_form.html
{% extends 'feed/base.html' %}

{% block content %}
	<div>
		<form action="" enctype="multipart/form-data" method="post">
			{% csrf_token %}
			{% include 'feed/form-template.html' %}
			<button class="btn btn-success">Update</button>
		</form>
	</div>
{% endblock %}